// Generated by gencpp from file turtlesim_following/TurtleVelocity.msg
// DO NOT EDIT!


#ifndef TURTLESIM_FOLLOWING_MESSAGE_TURTLEVELOCITY_H
#define TURTLESIM_FOLLOWING_MESSAGE_TURTLEVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_following
{
template <class ContainerAllocator>
struct TurtleVelocity_
{
  typedef TurtleVelocity_<ContainerAllocator> Type;

  TurtleVelocity_()
    : robot_name()
    , velocity(0.0)  {
    }
  TurtleVelocity_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleVelocity_

typedef ::turtlesim_following::TurtleVelocity_<std::allocator<void> > TurtleVelocity;

typedef boost::shared_ptr< ::turtlesim_following::TurtleVelocity > TurtleVelocityPtr;
typedef boost::shared_ptr< ::turtlesim_following::TurtleVelocity const> TurtleVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_following::TurtleVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_following::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtlesim_following::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_following::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtlesim_following::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6bb568f2540fd6c412734c452053a41";
  }

  static const char* value(const ::turtlesim_following::TurtleVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6bb568f2540fd6cULL;
  static const uint64_t static_value2 = 0x412734c452053a41ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_following/TurtleVelocity";
  }

  static const char* value(const ::turtlesim_following::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string robot_name\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::turtlesim_following::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_following::TurtleVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_following::TurtleVelocity_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_FOLLOWING_MESSAGE_TURTLEVELOCITY_H
